language: php

# Solr 6.x doesn't work with the Java versions included in "xenial" or "bionic".
dist: trusty

php:
  - 7.1
  - 7.3
  - 7.4

env:
  # Solr 8
  - SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=8.5.0 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=8.5.0 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
  # Solr 7
  - SOLR=7.7.2 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=7.7.2 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=7.7.2 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=7.7.2 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
  # Solr 6
  - SOLR=6.6.6 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
  - SOLR=6.6.6 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
  # Solr 5
  - SOLR=5.5.5 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=5.5.5 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=5.5.5 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
  # Solr 4
  - SOLR=4.5.1 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=4.5.1 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
  - SOLR=4.5.1 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false

git:
  # The depth needs to be increased. The default of 50 leads to fatal: reference
  # repository '/home/travis/.cache/composer/vcs/-home-travis-build-mkalkbrenner
  # -search-api-solr/' is shallow.
  depth: 10000

cache:
  directories:
    - $HOME/.composer/cache
    - solr_downloads

addons:
  mariadb: '10.4'

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer global require "hirak/prestissimo:^0.3"
  - ls solr_downloads/
  - wget -nc --continue -v --tries=3 --directory-prefix=solr_downloads "http://archive.apache.org/dist/lucene/solr/${SOLR}/solr-${SOLR}.tgz"
  - tar -xzf solr_downloads/solr-${SOLR}.tgz
  - mysql -e 'CREATE DATABASE drupal;'
  - patch -p1 < tests/no_deps.patch
  - git commit -m 'no deps' search_api_solr.info.yml
  - git tag 4.99.0

install:
  # Make sure we don't fail when checking out projects.
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.drupal.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get the Drupal core.
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth=1 --branch $DRUPAL https://git.drupal.org/project/drupal.git
  - cd $TRAVIS_BUILD_DIR/../drupal
  - patch -p1 < $TRAVIS_BUILD_DIR/tests/no_ext_dependencies.patch
  - composer install --ignore-platform-reqs
  - composer config repositories.search_api_solr vcs $TRAVIS_BUILD_DIR
  - |
    if [ ${DRUPAL} != "9.0.x" ]; then
      composer require --no-suggest --ignore-platform-reqs symfony/event-dispatcher:"4.3.4 as 3.4.99" drupal/composer_deploy
      composer run-script drupal-phpunit-upgrade
    fi
  - composer require --no-suggest --ignore-platform-reqs solarium/solarium:"$SOLARIUM" drupal/search_api:1.x-dev drupal/search_api_autocomplete:1.x-dev drupal/search_api_solr:4.99.0 drupal/facets:1.x-dev drush/drush:$DRUSH drupal/drush_language:1.x-dev drupal/devel:3.x-dev monolog/monolog
  # search_api_solr_location is not yet Drupal 9 ready
  # Solr 4 lacks the required features for search_api_location
  - |
    if [ ${DRUPAL} != "9.0.x" ] && [ ${SOLR} != "4.5.1" ]; then
      composer require --no-suggest --ignore-platform-reqs drupal/geofield:1.x-dev drupal/search_api_location:1.x-dev
    fi
  # Patch template.
  #########################################
  # to be removed once #2824932 is resolved
  #- cd modules/contrib/search_api
  #- curl https://www.drupal.org/files/issues/2018-12-20/3021717.patch | patch -p1
  #- cd $TRAVIS_BUILD_DIR/../drupal
  #########################################
  - cp $TRAVIS_BUILD_DIR/tests/travis.phpunit.xml $TRAVIS_BUILD_DIR/../drupal/core/phpunit.xml.dist

before_script:
  - export SOLR_INDEX_WAIT=4
  - export SYMFONY_DEPRECATIONS_HELPER=disabled
  # Start the built-in php web server (mysql is already started) and suppress
  # web server access logs output.
  - php -S localhost:8888 >& /dev/null &
  # Install the site.
  - ./vendor/bin/drush -v site-install minimal --db-url=mysql://root:@localhost/drupal --yes
  - ./vendor/bin/drush en --yes drush_language
  - ./vendor/bin/drush language-add ar
  - ./vendor/bin/drush language-add bg
  - ./vendor/bin/drush language-add ca
  - ./vendor/bin/drush language-add cs
  - ./vendor/bin/drush language-add da
  - ./vendor/bin/drush language-add de
  - ./vendor/bin/drush language-add el
  - ./vendor/bin/drush language-add es
  - ./vendor/bin/drush language-add et
  - ./vendor/bin/drush language-add fa
  - ./vendor/bin/drush language-add fi
  - ./vendor/bin/drush language-add fr
  - ./vendor/bin/drush language-add ga
  - ./vendor/bin/drush language-add hi
  - ./vendor/bin/drush language-add hr
  - ./vendor/bin/drush language-add id
  - ./vendor/bin/drush language-add it
  - ./vendor/bin/drush language-add ja
  - ./vendor/bin/drush language-add lv
  - ./vendor/bin/drush language-add nb
  - ./vendor/bin/drush language-add nl
  - ./vendor/bin/drush language-add nn
  - ./vendor/bin/drush language-add pl
  - ./vendor/bin/drush language-add pt-pt
  - ./vendor/bin/drush language-add pt-br
  - ./vendor/bin/drush language-add ro
  - ./vendor/bin/drush language-add ru
  - ./vendor/bin/drush language-add sk
  - ./vendor/bin/drush language-add sr
  - ./vendor/bin/drush language-add sv
  - ./vendor/bin/drush language-add th
  - ./vendor/bin/drush language-add tr
  - ./vendor/bin/drush language-add uk
  - ./vendor/bin/drush language-add zh-hans
  - ./vendor/bin/drush language-add zh-hant
  # Let dev versions fulfill module version dependencies.
  - |
    if [ ${DRUPAL} != "9.0.x" ]; then
      ./vendor/bin/drush en composer_deploy --yes
    fi
  # Generate a multilingual Solr configuration. Therefore we have to install the
  # test modules before the tests.
  - |
    if [ ${SOLR} == "5.5.5" ] || [ ${SOLR} == "4.5.1" ]; then
      ./vendor/bin/drush en --yes search_api_solr_legacy
    fi
  - cp -a core/modules/system/tests/modules/entity_test core/modules/system/entity_test
  - cp -a modules/contrib/search_api/tests/search_api_test_example_content modules/contrib/search_api/search_api_test_example_content
  - cp -a modules/contrib/search_api_solr/tests/modules/search_api_solr_test modules/contrib/search_api_solr/search_api_solr_test
  - ./vendor/bin/drush en --yes search_api_solr_test
  - |
      if [ ${SOLR_CLOUD} == "true" ]; then
        ./vendor/bin/drush -v solr-gsc solr_search_server_cloud conf.zip $SOLR
      else
        ./vendor/bin/drush -v solr-gsc solr_search_server conf.zip $SOLR
      fi
  - rm -rf core/modules/system/entity_test modules/contrib/search_api/search_api_test_example_content modules/contrib/search_api_solr/search_api_solr_test
  - |
    if [ ${SOLR} == "4.5.1" ]; then
      cd $TRAVIS_BUILD_DIR/solr-${SOLR}/example
      mkdir -p multicore/drupal
      unzip -o $TRAVIS_BUILD_DIR/../drupal/conf.zip -d multicore/drupal/conf
      # ls -lh multicore/drupal/conf
      cat multicore/drupal/conf/*.xml
      java -Djetty.port=8983 -Dsolr.solr.home=multicore -jar start.jar > /dev/null 2>&1 &
      sleep 20
      curl "http://localhost:8983/solr/admin/cores?action=CREATE&name=drupal&instanceDir=drupal&config=solrconfig.xml&schema=schema.xml&dataDir=data"
      tail logs/*
      cd -
    else
      mkdir -p $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf
      unzip -o conf.zip -d $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf
      # ls -lh $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf
      cat $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf/*.xml
      if [ ${SOLR_CLOUD} == "true" ]; then
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr start -e cloud -noprompt || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr delete -c gettingstarted || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr create -c techproducts -s 2 -rf 2 -d $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/configsets/sample_techproducts_configs/conf -n sample_techproducts_configs || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/post -c techproducts $TRAVIS_BUILD_DIR/solr-${SOLR}/example/exampledocs/*.xml || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr create -c drupal -s 2 -rf 2 -d $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf -n drupal || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr create -c checkpoints -s 1 -rf 2 || travis_terminate 1;
      else
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr start -e techproducts || travis_terminate 1;
        $TRAVIS_BUILD_DIR/solr-${SOLR}/bin/solr create -c drupal -d $TRAVIS_BUILD_DIR/solr-${SOLR}/server/solr/drupal/conf || travis_terminate 1;
      fi
    fi
script:
  # Run the tests within the drupal directory.
  - cd $TRAVIS_BUILD_DIR/../drupal
  - vendor/bin/phpunit --version
  - |
    if [ ${SOLR} == "4.5.1" ]; then
      vendor/bin/phpunit -c core --group search_api_solr --exclude-group not_solr4 modules/contrib/search_api_solr
    elif [ ${DRUPAL} == "9.0.x" ]; then
      vendor/bin/phpunit -c core --group search_api_solr --exclude-group not_drupal9 modules/contrib/search_api_solr
    else
      vendor/bin/phpunit -c core --group search_api_solr modules/contrib/search_api_solr
    fi

after_script:
  - |
    if [ -f $TRAVIS_BUILD_DIR/solr.error.log ]; then
      cat $TRAVIS_BUILD_DIR/solr.error.log;
    fi

#deploy:
#  provider: releases
#  api_key:
#    secure: "KIrsokvCttxcZQ36uUy+iLyRqyCG6sOVqq7/pZma1F6z5mpKkZChQV1yUWtVw52f1fDCKloRlj42foNCTE2JXg9/nej4qHtp9iSUklaq5+YpQRMTw2J+AWX9EiUvAl1YESOGskzk81aaahjon0Ckks6AHTF1qB+kgM/Dnmrut7A="
#  file: 'release.zip'
#  skip_cleanup: true
#  draft: true

matrix:
  exclude:
    - php: 7.1
      env: SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.1
      env: SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.1
      env: SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=8.5.0 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=7.7.2 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.1
      env: SOLR=7.7.2 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=7.7.2 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=6.6.6 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.1
      env: SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.1
      env: SOLR=5.5.5 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=5.5.5 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=4.5.1 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.1
      env: SOLR=4.5.1 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=7.7.2 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=7.7.2 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=7.7.2 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=6.6.6 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=6.6.6 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=5.5.5 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=5.5.5 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=4.5.1 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=4.5.1 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
  allow_failures:
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=8.5.0 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=7.7.2 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=true
    - php: 7.4
      env: SOLR=6.6.6 SOLARIUM=5.2.0 DRUPAL=8.9.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=5.5.5 SOLARIUM=5.1.6 DRUPAL=8.8.x DRUSH=^10.2.2 SOLR_CLOUD=false
    - php: 7.4
      env: SOLR=4.5.1 SOLARIUM="dev-master as 6.0.99" DRUPAL=9.0.x DRUSH=^10.2.2 SOLR_CLOUD=false
