version: '3'
services:
  solr5:
    image: solr:5
    ports:
      - "8983:8983"
    volumes:
      - ./config-set:/opt/solr/server/solr/configsets/drupal
    command: bash -c "solr start -c; solr create -c drupal -n drupal; solr restart -c -f"
