plugin.plugin_configuration.search_api_autocomplete_suggester.search_api_solr_autocomplete_suggester:
  type: mapping
  label: 'Search API Solr Suggester'
  mapping:
    search_api_solr/site_hash:
      type: integer
      label: 'Site hash'
    search_api/index:
      type: string
      label: 'Index ID'
    drupal/langcode:
      type: string
      label: 'Language'

plugin.plugin_configuration.search_api_autocomplete_suggester.search_api_solr_autocomplete_spellcheck:
  type: mapping
  label: 'Search API Solr Spellcheck'

plugin.plugin_configuration.search_api_autocomplete_suggester.search_api_solr_autocomplete_terms:
  type: plugin.plugin_configuration.search_api_autocomplete_suggester.server
  label: 'Search API Solr Terms'
