<?php

/**
 * @file
 * Provides development tools for Search API Solr.
 */

use Drupal\search_api\Query\QueryInterface as SearchApiQueryInterface;
use Drupal\search_api\Query\ResultSetInterface;
use Solarium\Core\Query\QueryInterface as SolariumQueryInterface;
use Solarium\QueryType\Select\Result\Result as SolariumResult;

/**
 * Implements hook_entity_type_alter().
 */
function search_api_solr_devel_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type_id => $entity_type) {
    if ($entity_type->hasViewBuilderClass() && $entity_type->hasLinkTemplate('canonical')) {
      $entity_type->setLinkTemplate('devel-solr', "/devel/$entity_type_id/{{$entity_type_id}}/solr");
    }
  }
}

/**
 * Implements hook_search_api_solr_query_alter().
 */
function search_api_solr_devel_search_api_solr_query_alter(SolariumQueryInterface $solarium_query, SearchApiQueryInterface $query) {
  $solarium_query->getDebug();
}

/**
 * Implements hook_search_api_solr_search_results_alter().
 */
function search_api_solr_devel_search_api_solr_search_results_alter(ResultSetInterface $result_set, SearchApiQueryInterface $query, SolariumResult $result) {
  $result_data = $result->getData();
  if (isset($result_data['debug'])) {
    /** @var \Drupal\devel\DevelDumperManagerInterface $dumper */
    $dumper = \Drupal::service('devel.dumper');
    $dumper->message($result_data['debug'], 'Solr Debug Output');
  }
}
